### ISSUE TITLE
Issue Checklist

### ISSUE THREAD

**Issue by leandrol3** [leandrol3/record_linkage#4]
### Descreva o problema que está tentando resolver

- [ ] realizar o teste unitário
- [ ] Checkar lista de dependências antes de emitir
- [x] realizar o teste integrado

**Comment by leandrol3** [comment]
Here are the estimates for this features
- Number of people 
- Number of days
